### ISSUE TITLE
Can't execute Go - not installed error - on Ubuntu 14.10.

### ISSUE THREAD

**Issue by davidhtims** [geosoft1/tools#3]
On a fresh install of Ubuntu 14.10 64ibt.

Ran the script in Terminal (without sudo) - everything seems okay. The folders and files are created.

Rebooted and, still in the terminal, Ubuntu says Go is not installed.

cd into the go/bin folder and I can see go but I still get the above error.

Thanks very much for this script - it will be great when I get it working.

**Comment by pavesi** [comment]
having the exact same issue as davidhtims

**Comment by geosoft1** [comment]
sorry for late answer. if i understand the problem, you want to use go compiler from Terminal, right? Ubuntu say:The program 'go' is currently not installed.
it's normal because the script not install compiler in clasic way with apt-get and link the go compiler only with liteide (see $HOME/liteide/share/liteide/liteenv/system.env) and the paths are accesible only from liteide.
in fact the initial ideea was to have a speed in development and i want to avoid working in terminal but work in liteide. but i can reconsider the idea if is useful.

**Comment by pavesi** [comment]
ahh that makes a lot of sense. 

thanks for the insight!

**Comment by geosoft1** [comment]
yeap,the installer is focused on very easy to use and speed in development. basicaly, is no need to use terminal. the customizer (liteide.ini.mini) proved to be very good in practice on some real projects that have been developed much faster than classical and i add a basic integration with github from ide.
